### ISSUE TITLE
404 error for http://builds.opentosca.org//ui/v2.0.0/opentosca.war

### ISSUE THREAD

**Issue by snsrirama** [OpenTOSCA/install.opentosca.org#12]
Hello,

Trying to install opentosca from http://install.opentosca.org/
The script ended at:

### Retreive, Configure, and Install UI
--2018-02-12 14:36:20--  http://builds.opentosca.org//ui/v2.0.0/opentosca.war

ERROR 404: Not Found.

Thanks & Regards,
Satish

**Comment by koppor** [comment]
Which script did you use?

There seems to be a type as http://builds.opentosca.org/ui/v2.0.0/opentosca.war works.

For trying out, we currently recommend to use https://github.com/OpenTOSCA/opentosca-docker.

**Comment by snsrirama** [comment]
Thank you for your quick response. Yes. There is a typo. 
I am directly using the command:
wget -qO- http://install.opentosca.org/install | sh

**Comment by miwurster** [comment]
Fixed with latest PR #13.
